"""Add id column to amazon_products_combined

Revision ID: a71d298402e5
Revises: f508b79ac1d2
Create Date: 2024-12-06 02:23:57.204039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a71d298402e5'
down_revision = 'f508b79ac1d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product')
    op.drop_table('amazon_product')
    with op.batch_alter_table('amazon_products_combined', schema=None) as batch_op:
        batch_op.drop_column('unnamed:_0')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('amazon_products_combined', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unnamed:_0', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))

    op.create_table('amazon_product',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('main_category', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('sub_category', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('ratings', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('no_of_ratings', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('discount_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('actual_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('discount_percentage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='amazon_product_pkey')
    )
    op.create_table('product',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='product_pkey')
    )
    # ### end Alembic commands ###
